"""Tasks: goal + a fresh driver + a deterministic success check.

Designed for the tokens/cost/time/goal-conditioning/success benchmark:

- Three PAGE-SIZE buckets (small 15, medium 60, large 200 items). Bigger pages
  amplify the token/cost gap (a generic snapshot grows with the page; a
  goal-conditioned view stays small) and are where a success gap is most likely.
- Multiple colors per size = SAME page, DIFFERENT goal. That's the goal-conditioning
  showcase: on one page, the AgentView changes per goal while a generic snapshot
  is identical. The large bucket is weighted heavier (success signal lives there).

Checks read only deterministic driver state -- never an LLM.
"""
from __future__ import annotations

import pathlib
from dataclasses import dataclass
from typing import Any, Callable

from driver import (
    FakeShopDriver,
    FakeTrapShopDriver,
    build_products,
    build_ranked_products,
)

# file:// URLs for the PlaywrightDriver, one per demo site.
_SITES_DIR = pathlib.Path(__file__).parent / "sites"
SITES: dict[str, str] = {
    "shop": (_SITES_DIR / "shop" / "index.html").as_uri(),
    "form": (_SITES_DIR / "form" / "index.html").as_uri(),
    "docs": (_SITES_DIR / "docs" / "index.html").as_uri(),
    # size buckets (generated by gen_sites.py) -- real pages for Playwright + MCP
    "shop_15": (_SITES_DIR / "shop_15" / "index.html").as_uri(),
    "shop_60": (_SITES_DIR / "shop_60" / "index.html").as_uri(),
    "shop_200": (_SITES_DIR / "shop_200" / "index.html").as_uri(),
    # hard bucket: trap shops (wishlist decoy button before every cart button)
    "shop_trap_60": (_SITES_DIR / "shop_trap_60" / "index.html").as_uri(),
    "shop_trap_200": (_SITES_DIR / "shop_trap_200" / "index.html").as_uri(),
    # compute bucket: distinct per-color prices so ranking goals are unambiguous
    "shop_rank_60": (_SITES_DIR / "shop_rank_60" / "index.html").as_uri(),
    "shop_rank_200": (_SITES_DIR / "shop_rank_200" / "index.html").as_uri(),
}


@dataclass
class Task:
    id: str
    goal: str
    make_driver: Callable[[], Any]
    check: Callable[[Any], bool]  # given the final driver, did we succeed?
    site: str = "shop"
    size: int = 0  # catalog size (page-size bucket); 0 = n/a
    bucket: str = ""  # scoreboard grouping label; defaults to str(size)


def _cheapest_of_color(color: str) -> Callable[[Any], bool]:
    def check(driver) -> bool:
        st = driver.state()
        matching = [p for p in st["products"] if p["color"] == color]
        return bool(matching) and min(matching, key=lambda p: p["price"])["id"] in st["cart"]
    return check


def _nth_cheapest_of_color(color: str, n: int) -> Callable[[Any], bool]:
    """The item at rank n when the color's items are sorted cheapest-first."""
    def check(driver) -> bool:
        st = driver.state()
        matching = sorted((p for p in st["products"] if p["color"] == color),
                          key=lambda p: p["price"])
        return len(matching) >= n and matching[n - 1]["id"] in st["cart"]
    return check


def _cheapest_of_color_above(color: str, threshold: int) -> Callable[[Any], bool]:
    """The cheapest item of the color whose price is strictly above the threshold."""
    def check(driver) -> bool:
        st = driver.state()
        matching = sorted((p for p in st["products"]
                           if p["color"] == color and p["price"] > threshold),
                          key=lambda p: p["price"])
        return bool(matching) and matching[0]["id"] in st["cart"]
    return check


def _shop_of_size(n: int):
    """A fresh shop driver with an n-item catalog (deterministic)."""
    return lambda: FakeShopDriver(build_products(n))


def _trap_shop_of_size(n: int):
    """Same catalog, but every product has a wishlist decoy before its cart button."""
    return lambda: FakeTrapShopDriver(build_products(n))


# (bucket label, catalog size, colors to target on that page)
_BUCKETS = [
    ("small", 15, ["blue", "red", "green"]),
    ("medium", 60, ["blue", "red", "green", "black"]),
    ("large", 200, ["blue", "red", "green", "black", "white"]),
]

TASKS: dict[str, Task] = {}
_i = 1
for _label, _n, _colors in _BUCKETS:
    for _c in _colors:
        _id = f"t{_i:02d}_{_label}_cheapest_{_c}"
        TASKS[_id] = Task(
            id=_id,
            goal=f"Add the cheapest {_c} item to the cart",
            make_driver=_shop_of_size(_n),
            check=_cheapest_of_color(_c),
            site=f"shop_{_n}",  # real page for --driver playwright / MCP
            size=_n,
            bucket=f"{_label}-{_n}",
        )
        _i += 1

# --- Hard bucket: trap shops. Same "cheapest {color}" goal, but each product now
# has an "Add to wishlist" decoy button BEFORE its "Add to cart" button. Success
# still requires the item in the CART (wishlist doesn't count). A raw/MCP agent
# scanning look-alike buttons can mis-click the trap; a task-conditioned view only
# ever surfaces add_to_cart, so it can't be trapped. This is where a SUCCESS gap
# (not just an efficiency gap) should appear.
_TRAP_BUCKETS = [
    (60, ["blue", "red"]),
    (200, ["blue", "red"]),
]
for _n, _colors in _TRAP_BUCKETS:
    for _c in _colors:
        _id = f"t{_i:02d}_trap{_n}_cheapest_{_c}"
        TASKS[_id] = Task(
            id=_id,
            goal=f"Add the cheapest {_c} item to the cart",
            make_driver=_trap_shop_of_size(_n),
            check=_cheapest_of_color(_c),
            site=f"shop_trap_{_n}",
            size=_n,
            bucket=f"trap-{_n}",
        )
        _i += 1


def _ranked_shop_of_size(n: int):
    """Shop with distinct per-color prices (for unambiguous ranking goals)."""
    return lambda: FakeShopDriver(build_ranked_products(n))


# --- Compute bucket: goals that need RANKING / FILTERING over the candidate set,
# not just a keyword match. On raw, the agent must find every blue item among N,
# sort by price, and pick correctly -- error-prone as N grows. A goal-conditioned
# view hands it the pre-filtered blue items, so it ranks over a tiny set. This is
# the least-contrived place a real success gap can open (reasoning over noise).
_COMPUTE_BUCKETS = [60, 200]
for _n in _COMPUTE_BUCKETS:
    TASKS[f"t{_i:02d}_compute{_n}_3rd_cheapest_blue"] = Task(
        id=f"t{_i:02d}_compute{_n}_3rd_cheapest_blue",
        goal="Add the 3rd cheapest blue item to the cart",
        make_driver=_ranked_shop_of_size(_n),
        check=_nth_cheapest_of_color("blue", 3),
        site=f"shop_rank_{_n}",
        size=_n,
        bucket=f"compute-{_n}",
    )
    _i += 1
    TASKS[f"t{_i:02d}_compute{_n}_cheapest_blue_above_50"] = Task(
        id=f"t{_i:02d}_compute{_n}_cheapest_blue_above_50",
        goal="Add the cheapest blue item priced above $50 to the cart",
        make_driver=_ranked_shop_of_size(_n),
        check=_cheapest_of_color_above("blue", 50),
        site=f"shop_rank_{_n}",
        size=_n,
        bucket=f"compute-{_n}",
    )
    _i += 1
