"""Parity test: the Python validator must reproduce the Node validator's
verdict on EVERY fixture in data/fixtures/validator-parity.json (generated by
scripts/dump-validator-fixtures.js from the golden manifest, the smoke
manifest, and the hand-reconstructed negative suite).

For invalid fixtures, at least one expected error substring must appear in the
Python validator's errors (case-insensitive, matching check-negative.js).

Run standalone:  python pipeline/reward/test_parity.py
Or via pytest:   pytest pipeline/reward/test_parity.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from validator import validate  # noqa: E402

FIXTURES_PATH = Path(__file__).resolve().parents[2] / "data" / "fixtures" / "validator-parity.json"


def load_fixtures():
    return json.loads(FIXTURES_PATH.read_text(encoding="utf-8"))


def check_fixture(fx) -> list[str]:
    """Returns a list of parity failures for one fixture (empty = pass)."""
    problems = []
    valid, errors = validate(fx["output"], fx["trimmed_html"], fx["raw_html"])
    if valid != fx["expected_valid"]:
        problems.append(
            f"verdict mismatch: expected valid={fx['expected_valid']}, got valid={valid}; errors={errors}"
        )
    elif not fx["expected_valid"]:
        subs = fx["expected_error_substrings"]
        lowered = [e.lower() for e in errors]
        if not any(sub.lower() in e for sub in subs for e in lowered):
            problems.append(
                f"expected an error mentioning one of {subs!r}, got errors={errors}"
            )
    return problems


def test_parity():
    fixtures = load_fixtures()
    assert fixtures, f"no fixtures found at {FIXTURES_PATH}"
    failures = []
    for fx in fixtures:
        for p in check_fixture(fx):
            failures.append(f"{fx['name']}: {p}")
    assert not failures, "parity failures:\n" + "\n".join(failures)


def main() -> int:
    fixtures = load_fixtures()
    failed = 0
    for fx in fixtures:
        problems = check_fixture(fx)
        ok = not problems
        if not ok:
            failed += 1
        print(f"{'PASS' if ok else 'FAIL'}  {fx['name']}")
        for p in problems:
            print(f"      {p}")
    n = len(fixtures)
    print(
        f"\n{n - failed}/{n} fixtures match the Node validator."
        + ("" if failed == 0 else f"  {failed} PARITY FAILURE(S).")
    )
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
